name: Build

on:
  push:
    branches:
      - feat-git-actions

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4

      - run: npm install

      - name: Install Whiskers
        run: cargo install catppuccin-whiskers

      - name: Generate colors
        run: whiskers colors.tera

      - name: Build the theme
        run: |
          mkdir -p dists
          
          for flavor in $(ls src/generated/colors); do
            for accent in $(ls src/generated/colors/$flavor); do
              echo "Building $flavor/$accent"
              mkdir -p temp_build
              cp src/generated/colors/$flavor/$accent src/colors.scss
              npm run build
              mv dist/* temp_build/
              rm src/colors.scss
              zip -r "dists/Catppuccin-${flavor}-${accent%.scss}.zip" temp_build/*
              rm -rf temp_build
            done
          done

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dists/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "release-${{ github.run_number }}"
          prerelease: true
          name: "Latest Build"