name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4

      - run: npm install

      - name: Install Whiskers
        run: cargo install catppuccin-whiskers

      - name: Generate colors
        run: whiskers colors.tera

      - name: Build the theme
        run: |
          mkdir -p dists
          
          for flavor in $(ls src/generated/colors); do
            for accent in $(ls src/generated/colors/$flavor); do
              echo "Building $flavor/$accent"
              mkdir -p catppuccin
              cp src/generated/colors/$flavor/$accent src/colors.scss
              npm run build
              mv dist/* catppuccin/
              rm src/colors.scss
              zip -r "dists/Catppuccin-${flavor}-${accent%.scss}.zip" catppuccin/*
              rm -rf catppuccin
            done
          done

      - name: Create or update the latest tag
        run: |
          # Ensure we have the latest code
          git fetch --tags

          # Check if the 'latest' tag already exists
          if git rev-parse "refs/tags/latest" >/dev/null 2>&1; then
            echo "Tag 'latest' exists, updating it."
            git tag -d latest # Delete the old 'latest' tag locally
            git push origin --delete latest # Delete the old 'latest' tag remotely
          fi

          # Create the 'latest' tag pointing to the latest commit
          git tag latest
          git push origin latest # Push the new 'latest' tag
      
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dists/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "latest"
          prerelease: false
          name: "[Latest] Catppuccin for LiquidBounce"